version: '3'

services:
    nginx:
        build:
            context: .
        volumes: 
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            #- ./pages:/var/www/html/user/pages
            - ${DATA}:/var/www/html/user/data
        ports:
            - "${PORT}:8080"
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
